{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8-namespace-reaper.fullname" . }}
  namespace: {{ include "k8-namespace-reaper.namespace" . | quote }}
  labels:
    {{- include "k8-namespace-reaper.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8-namespace-reaper.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8-namespace-reaper.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
