{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8-namespace-reaper.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "k8-namespace-reaper.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - delete
{{- end }}
