{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8-namespace-reaper.serviceAccountName" . }}
  namespace: {{ include "k8-namespace-reaper.namespace" . | quote }}
  labels:
    {{- include "k8-namespace-reaper.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
