apiVersion: v1
kind: Namespace
metadata:
  name: k8-namespace-reaper
  labels:
    app.kubernetes.io/name: k8-namespace-reaper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8-namespace-reaper
  namespace: k8-namespace-reaper
  labels:
    app.kubernetes.io/name: k8-namespace-reaper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8-namespace-reaper
  namespace: k8-namespace-reaper
  labels:
    app.kubernetes.io/name: k8-namespace-reaper
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8-namespace-reaper
  namespace: k8-namespace-reaper
  labels:
    app.kubernetes.io/name: k8-namespace-reaper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8-namespace-reaper
subjects:
- kind: ServiceAccount
  name: k8-namespace-reaper
  namespace: k8-namespace-reaper
