---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ondemand-k8-namespace-reaper
  namespace: k8-namespace-reaper
  labels:
    app.kubernetes.io/name: k8-namespace-reaper
    app.kubernetes.io/instance: ondemand-k8-namespace-reaper
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: ondemand-k8-namespace-reaper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8-namespace-reaper
        app.kubernetes.io/instance: ondemand-k8-namespace-reaper
    spec:
      serviceAccountName: k8-namespace-reaper
      containers:
      - name: ondemand-k8-namespace-reaper
        image: quay.io/ohiosupercomputercenter/k8-namespace-reaper:latest
        imagePullPolicy: Always
        args:
        - --prometheus-address=http://prometheus:9090
        - --namespace-labels=app.kubernetes.io/name=open-ondemand
        - --namespace-last-used-annotation=openondemand.org/last-hook-execution
        - --listen-address=:8080
        - --log-level=info
        - --log-format=logfmt
        ports:
        - containerPort: 8080
          name: metrics
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 50Mi
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: ondemand-k8-namespace-reaper
  namespace: k8-namespace-reaper
  labels:
    app.kubernetes.io/name: k8-namespace-reaper
    app.kubernetes.io/instance: ondemand-k8-namespace-reaper
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    app.kubernetes.io/instance: ondemand-k8-namespace-reaper
